#!/usr/bin/env kotlinr

/**
 * Generates TzdbData.kt from an OpenJDK tzdb.dat file.
 *
 * Usage:
 *   kotlinr tools/generate-tzdb-data.main.kts <tzdb.dat> <TzdbData.kt>
 */

import java.io.File
import java.util.Base64
import kotlin.system.exitProcess

val input = args.getOrNull(0)
val output = args.getOrNull(1)
if (input == null || output == null) {
    System.err.println("usage: generate-tzdb-data.main.kts <tzdb.dat> <TzdbData.kt>")
    exitProcess(1)
}

val encoded = Base64.getEncoder().encodeToString(File(input).readBytes())
val body = encoded.chunked(48000).joinToString(",\n") { chunk ->
    val lines = chunk.chunked(120).joinToString("\n")
    "    \"\"\"\n$lines\n    \"\"\""
}

val source = """
package io.heapy.grogu.time.zone

// Generated by tools/generate-tzdb-data.main.kts from an OpenJDK 21 tzdb.dat.
// The data is split to stay below JVM class-file string constant limits.
internal val BUNDLED_TZDB_BASE64: Array<String> = arrayOf(
$body,
)
""".trimStart('\n')

File(output).writeText(source)
