#!/usr/bin/env kotlinr

/**
 * Generates HijrahUmmAlQuraData.kt from OpenJDK's Umm al-Qura configuration.
 *
 * Usage:
 *   kotlinr tools/generate-hijrah-data.main.kts <hijrah-config.properties> <HijrahUmmAlQuraData.kt>
 */

import java.io.File
import java.time.LocalDate
import kotlin.system.exitProcess

fun abort(message: String): Nothing {
    System.err.println(message)
    exitProcess(1)
}

val input = args.getOrNull(0)
val output = args.getOrNull(1)
if (input == null || output == null) {
    abort("usage: generate-hijrah-data.main.kts <hijrah-config.properties> <HijrahUmmAlQuraData.kt>")
}

val metadata = mutableMapOf<String, String>()
val years = mutableMapOf<Int, List<Int>>()
File(input).forEachLine { rawLine ->
    val line = rawLine.trim()
    if (line.isEmpty() || line.startsWith("#")) return@forEachLine

    val key = line.substringBefore("=")
    if (!line.contains("=")) abort("invalid property: $line")
    val value = line.substringAfter("=")

    if (key.matches(Regex("\\d+"))) {
        val months = value.split(Regex("\\s+")).filter { it.isNotEmpty() }.map { it.toInt() }
        if (months.size != 12) abort("year $key must contain 12 months")
        if (!months.all { it == 29 || it == 30 }) abort("year $key contains an invalid month length")
        years[key.toInt()] = months
    } else {
        metadata[key] = value
    }
}

if (metadata["id"] != "Hijrah-umalqura") abort("unexpected chronology id")
if (metadata["type"] != "islamic-umalqura") abort("unexpected calendar type")
if (metadata["version"] == null) abort("missing version")
if (years.isEmpty()) abort("missing calendar years")

val minYear = years.keys.min()
val maxYear = years.keys.max()
val expectedYears = (minYear..maxYear).toList()
if (years.keys.sorted() != expectedYears) abort("calendar years must be contiguous")

val monthLengths = expectedYears.flatMap { years.getValue(it) }
val monthBits = monthLengths.joinToString("") { if (it == 30) "1" else "0" }
val bitsSource = monthBits.chunked(120).joinToString(" +\n") { "    \"$it\"" }

val isoStart = LocalDate.parse(metadata.getValue("iso-start"))
val epochDay = isoStart.toEpochDay().toInt()
val maxEpochDay = epochDay + monthLengths.sum()
val yearLengths = expectedYears.map { years.getValue(it).sum() }

val source = """
package io.heapy.krogu.time.chrono

// Generated by tools/generate-hijrah-data.main.kts from OpenJDK 21's
// hijrah-config-Hijrah-umalqura_islamic-umalqura.properties.
internal const val HIJRAH_UMM_AL_QURA_VERSION: String = "${metadata.getValue("version")}"
internal const val HIJRAH_UMM_AL_QURA_MIN_YEAR: Int = $minYear
internal const val HIJRAH_UMM_AL_QURA_MAX_YEAR: Int = $maxYear
internal const val HIJRAH_UMM_AL_QURA_MIN_EPOCH_DAY: Int = $epochDay
internal const val HIJRAH_UMM_AL_QURA_MAX_EPOCH_DAY: Int = $maxEpochDay
internal const val HIJRAH_UMM_AL_QURA_MIN_MONTH_LENGTH: Int = ${monthLengths.min()}
internal const val HIJRAH_UMM_AL_QURA_MAX_MONTH_LENGTH: Int = ${monthLengths.max()}
internal const val HIJRAH_UMM_AL_QURA_MAX_YEAR_LENGTH: Int = ${yearLengths.max()}

// One bit per month in chronological order: 0 means 29 days, 1 means 30 days.
internal const val HIJRAH_UMM_AL_QURA_MONTH_BITS: String =
$bitsSource
""".trimStart('\n')

File(output).writeText(source)
