#!/usr/bin/env ruby
# frozen_string_literal: true

require "base64"

input, output = ARGV
abort "usage: generate-tzdb-data.rb <tzdb.dat> <TzdbData.kt>" unless input && output

encoded = Base64.strict_encode64(File.binread(input))
chunks = encoded.scan(/.{1,48000}/)
body = chunks.map do |chunk|
  lines = chunk.scan(/.{1,120}/).join("\n")
  "    \"\"\"\n#{lines}\n    \"\"\""
end.join(",\n")

source = <<~KOTLIN
  package io.heapy.grogu.time.zone

  // Generated by tools/generate-tzdb-data.rb from an OpenJDK 21 tzdb.dat.
  // The data is split to stay below JVM class-file string constant limits.
  internal val BUNDLED_TZDB_BASE64: Array<String> = arrayOf(
  #{body},
  )
KOTLIN

File.write(output, source)
