#!/usr/bin/env ruby
# frozen_string_literal: true

require "date"

input, output = ARGV
abort "usage: generate-hijrah-data.rb <hijrah-config.properties> <HijrahUmmAlQuraData.kt>" unless input && output

metadata = {}
years = {}
File.foreach(input) do |line|
  line = line.strip
  next if line.empty? || line.start_with?("#")

  key, value = line.split("=", 2)
  abort "invalid property: #{line}" unless value

  if key.match?(/\A\d+\z/)
    months = value.split.map(&:to_i)
    abort "year #{key} must contain 12 months" unless months.length == 12
    abort "year #{key} contains an invalid month length" unless months.all? { |length| [29, 30].include?(length) }
    years[key.to_i] = months
  else
    metadata[key] = value
  end
end

abort "unexpected chronology id" unless metadata["id"] == "Hijrah-umalqura"
abort "unexpected calendar type" unless metadata["type"] == "islamic-umalqura"
abort "missing version" unless metadata["version"]
abort "missing calendar years" if years.empty?

min_year, max_year = years.keys.minmax
expected_years = (min_year..max_year).to_a
abort "calendar years must be contiguous" unless years.keys.sort == expected_years

month_lengths = expected_years.flat_map { |year| years.fetch(year) }
month_bits = month_lengths.map { |length| length == 30 ? "1" : "0" }.join
chunks = month_bits.scan(/.{1,120}/)
bits_source = chunks.map { |chunk| "    \"#{chunk}\"" }.join(" +\n")

iso_start = Date.iso8601(metadata.fetch("iso-start"))
epoch_day = (iso_start - Date.new(1970, 1, 1)).to_i
max_epoch_day = epoch_day + month_lengths.sum
year_lengths = expected_years.map { |year| years.fetch(year).sum }

source = <<~KOTLIN
  package io.heapy.grogu.time.chrono

  // Generated by tools/generate-hijrah-data.rb from OpenJDK 21's
  // hijrah-config-Hijrah-umalqura_islamic-umalqura.properties.
  internal const val HIJRAH_UMM_AL_QURA_VERSION: String = "#{metadata.fetch("version")}"
  internal const val HIJRAH_UMM_AL_QURA_MIN_YEAR: Int = #{min_year}
  internal const val HIJRAH_UMM_AL_QURA_MAX_YEAR: Int = #{max_year}
  internal const val HIJRAH_UMM_AL_QURA_MIN_EPOCH_DAY: Int = #{epoch_day}
  internal const val HIJRAH_UMM_AL_QURA_MAX_EPOCH_DAY: Int = #{max_epoch_day}
  internal const val HIJRAH_UMM_AL_QURA_MIN_MONTH_LENGTH: Int = #{month_lengths.min}
  internal const val HIJRAH_UMM_AL_QURA_MAX_MONTH_LENGTH: Int = #{month_lengths.max}
  internal const val HIJRAH_UMM_AL_QURA_MAX_YEAR_LENGTH: Int = #{year_lengths.max}

  // One bit per month in chronological order: 0 means 29 days, 1 means 30 days.
  internal const val HIJRAH_UMM_AL_QURA_MONTH_BITS: String =
  #{bits_source}
KOTLIN

File.write(output, source)
